name = "Vo"
uuid = "46916a23-5c37-4b23-b62b-45b422578c04"
version = "0.1.0"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]

[deps]
Agentif = "b1e21dde-9d8e-492f-89d0-ee48af23bfc5"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LLMTools = "d2f4c4b3-4b8a-4e8c-9b4f-7b8e4e6e5b2c"
LocalSearch = "3edf9609-13f2-4288-b0a3-8bd6d521158e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MSTeams = "730ab40b-c28c-4fcb-83ce-ff189233d76d"
Mattermost = "c9a394b0-b131-4b99-aeb4-b011b7b7f934"
PtySessions = "581b29ee-4021-4243-bea3-a8421693f905"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
Signal = "0944c9af-6677-4ce2-950b-62b1fa25f333"
Slack = "4d517630-ce0d-4555-8fa7-416d9f8f5684"
Telegram = "0f099131-46f3-42ed-8989-d9c7888465f9"
Tempus = "e6262be2-5787-4bdc-bc3f-4b5a3442fa30"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[sources]
Agentif = {path = "../Agentif"}
ConcurrentUtilities = {url = "https://github.com/JuliaServices/ConcurrentUtilities.jl.git", rev = "main"}
HTTP = {rev = "master", url = "https://github.com/JuliaWeb/HTTP.jl.git"}
LLMTools = {path = "../LLMTools"}
LocalSearch = {url = "https://github.com/quinnj/LocalSearch.jl.git"}
MSTeams = {url = "https://github.com/quinnj/MSTeams.jl.git"}
Mattermost = {url = "https://github.com/quinnj/Mattermost.jl.git"}
PtySessions = {url = "https://github.com/quinnj/PtySessions.jl.git"}
Signal = {url = "https://github.com/quinnj/Signal.jl.git"}
Slack = {url = "https://github.com/quinnj/Slack.jl.git"}
Telegram = {url = "https://github.com/quinnj/Telegram.jl.git"}
Tempus = {url = "https://github.com/JuliaServices/Tempus.jl.git"}

[compat]
Agentif = "1"
HTTP = "1"
LLMTools = "1"
ScopedValues = "1.5"
julia = "1.10"

[extras]
ConcurrentUtilities = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
