name = "Vo"
uuid = "46916a23-5c37-4b23-b62b-45b422578c04"
version = "0.1.0"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]

[deps]
Agentif = "b1e21dde-9d8e-492f-89d0-ee48af23bfc5"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LLMTools = "d2f4c4b3-4b8a-4e8c-9b4f-7b8e4e6e5b2c"
LocalSearch = "3edf9609-13f2-4288-b0a3-8bd6d521158e"
Mattermost = "c9a394b0-b131-4b99-aeb4-b011b7b7f934"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
Tempus = "e6262be2-5787-4bdc-bc3f-4b5a3442fa30"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[weakdeps]
MSTeams = "730ab40b-c28c-4fcb-83ce-ff189233d76d"
Signal = "0944c9af-6677-4ce2-950b-62b1fa25f333"
Slack = "4d517630-ce0d-4555-8fa7-416d9f8f5684"
Telegram = "0f099131-46f3-42ed-8989-d9c7888465f9"

[sources]
Agentif = {path = "../Agentif"}
LLMTools = {path = "../LLMTools"}
LocalSearch = {url = "https://github.com/quinnj/LocalSearch.jl.git"}
MSTeams = {url = "https://github.com/quinnj/MSTeams.jl.git"}
Mattermost = {url = "https://github.com/quinnj/Mattermost.jl.git"}
Signal = {url = "https://github.com/quinnj/Signal.jl.git"}
Slack = {url = "https://github.com/quinnj/Slack.jl.git"}
Telegram = {url = "https://github.com/quinnj/Telegram.jl.git"}
Tempus = {url = "https://github.com/JuliaServices/Tempus.jl.git", rev = "main"}

[extensions]
VoMSTeamsExt = "MSTeams"
VoMattermostExt = "Mattermost"
VoSignalExt = "Signal"
VoSlackExt = "Slack"
VoTelegramExt = "Telegram"

[compat]
Agentif = "1"
MSTeams = "0.1.0"
Mattermost = "0.1.0"
Signal = "0.1.0"
Slack = "0.1.0"
Telegram = "0.1.0"
TimeZones = "1"
julia = "1.10"

[extras]
MSTeams = "730ab40b-c28c-4fcb-83ce-ff189233d76d"
Mattermost = "c9a394b0-b131-4b99-aeb4-b011b7b7f934"
Signal = "0944c9af-6677-4ce2-950b-62b1fa25f333"
Slack = "4d517630-ce0d-4555-8fa7-416d9f8f5684"
Telegram = "0f099131-46f3-42ed-8989-d9c7888465f9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MSTeams", "Mattermost", "Signal", "Slack", "Telegram"]
