name = "LLMProviders"
uuid = "e1f4c4b3-4b8a-4e8c-9b4f-7b8e4e6e5b2a"
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
StructUtils = "ec057cc2-7a8d-4b58-b3b3-92acb9f63b42"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[sources]
JSONSchema = {url = "https://github.com/JuliaIO/JSONSchema.jl.git"}

[compat]
HTTP = "1"
JSON = "1.3"
JSONSchema = "2"
Logging = "1.11"
StructUtils = "2.6"
UUIDs = "1.11.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
