name = "Juco"
uuid = "a4f4c4b3-4b8a-4e8c-9b4f-7b8e4e6e5b2e"
version = "0.1.0"

[deps]
Agentif = "b1e21dde-9d8e-492f-89d0-ee48af23bfc5"
LLMTools = "d2f4c4b3-4b8a-4e8c-9b4f-7b8e4e6e5b2c"

[sources]
Agentif = {path = "../Agentif"}
LLMTools = {path = "../LLMTools"}

[compat]
Agentif = "1"
LLMTools = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
