name = "Agentif"
uuid = "b1e21dde-9d8e-492f-89d0-ee48af23bfc5"
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
StructUtils = "ec057cc2-7a8d-4b58-b3b3-92acb9f63b42"

[sources]
HTTP = {path = "../HTTP"}
JSON = {path = "../JSON"}

[compat]
HTTP = "1.10.19"
InteractiveUtils = "1.11.0"
JSON = "1.3.0"
Logging = "1.11.0"
StructUtils = "2.6.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
