name = "LLMOAuth"
uuid = "f3f4c4b3-4b8a-4e8c-9b4f-7b8e4e6e5b2d"
version = "1.0.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OAuth = "22d8b318-f366-56fb-a292-a93f7d76c017"

[sources]
OAuth = {url = "https://github.com/JuliaServices/OAuth.jl.git", rev = "main"}

[compat]
HTTP = "1"
JSON = "1.3"
OAuth = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
