name = "Agentif"
uuid = "b1e21dde-9d8e-492f-89d0-ee48af23bfc5"
version = "1.0.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Encid = "22e113d6-bca1-46f4-8715-c46169ad70b7"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
LLMProviders = "e1f4c4b3-4b8a-4e8c-9b4f-7b8e4e6e5b2a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PtySessions = "581b29ee-4021-4243-bea3-a8421693f905"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
StructUtils = "ec057cc2-7a8d-4b58-b3b3-92acb9f63b42"

[weakdeps]
MSTeams = "730ab40b-c28c-4fcb-83ce-ff189233d76d"
Mattermost = "c9a394b0-b131-4b99-aeb4-b011b7b7f934"
Signal = "0944c9af-6677-4ce2-950b-62b1fa25f333"
Slack = "4d517630-ce0d-4555-8fa7-416d9f8f5684"
Telegram = "0f099131-46f3-42ed-8989-d9c7888465f9"

[extensions]
AgentifMSTeamsExt = "MSTeams"
AgentifMattermostExt = "Mattermost"
AgentifSignalExt = "Signal"
AgentifSlackExt = "Slack"
AgentifTelegramExt = "Telegram"

[sources]
LLMProviders = {path = "../LLMProviders"}
JSON = {path = "../../JSON"}
JSONSchema = {path = "../../JSONSchema"}
PtySessions = {path = "../../PtySessions"}
Encid = {path = "../../Encid"}
HTTP = {path = "/Users/jacob.quinn/.julia/packages/HTTP/na214"}
MSTeams = {path = "../../MSTeams"}
Mattermost = {path = "../../Mattermost"}
Signal = {path = "../../Signal"}
Slack = {path = "../../Slack"}
Telegram = {path = "../../Telegram"}

[compat]
Encid = "1.0.0"
HTTP = "1"
InteractiveUtils = "1"
JSON = "1.3"
JSONSchema = "2"
LLMProviders = "1"
Logging = "1"
PtySessions = "0.1"
ScopedValues = "1.5"
StructUtils = "2.6"
julia = "1.8"

[extras]
MSTeams = "730ab40b-c28c-4fcb-83ce-ff189233d76d"
Mattermost = "c9a394b0-b131-4b99-aeb4-b011b7b7f934"
Signal = "0944c9af-6677-4ce2-950b-62b1fa25f333"
Slack = "4d517630-ce0d-4555-8fa7-416d9f8f5684"
Telegram = "0f099131-46f3-42ed-8989-d9c7888465f9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
